# -*- coding: utf-8 -*-
"""kz_slice.py -- the `slice` stage (design §6 step 11, §5.4).

WHAT §6 STEP 11 ASKS THIS SUITE TO COVER, LITERALLY
    "`test_koreanize_slice.py` covers `(1,1)`, `(10,7)` and a non-integral
     division that must refuse."

    Those three are the whole point of the stage's existence, because they are
    exactly what `slice-atlases.py` could not do. That script carries
    `EXPECTED_SHEET_DIMS` at `:48-53` -- three hand-recorded tuples -- and
    `CELL_W, CELL_H = 750, 1050` at `:46`, so a `(1,1)` sheet is a `KeyError`, a
    `(10,7)` sheet is a `KeyError`, and a sheet whose pixels do not divide by its
    grid is a silent off-by-N crop that produces plausible-looking cards.
    `test_one_by_one_*`, `test_ten_by_seven_*` and `test_non_integral_*` below
    are the three cases R-A is mitigated by, and `test_module_declares_no_cell_
    size_table` is what stops the table growing back.

WHY EVERY CASE BUILDS ITS OWN PIXELS
    §5.9 marks corpus-dependent tests `needs_golden` and skips them when the
    2.1 GB fixture is absent -- so a suite resting on it has zero passing
    evidence on any machine without the corpus, which is the position
    `test_koreanize_checkers.py`'s header describes W1 being rescued from. Every
    image below is generated by `kz_slice.synth_atlas`, which paints a DIFFERENT
    colour per cell: on a uniform sheet every crop is identical and no assertion
    here could tell a correct slice from an off-by-one one.

WHY THE SANDBOX AND NOT A HAND-WRITTEN run_dir
    `slice` reads a hash-pinned `scenario.json`, `atlas-inventory.json` and
    `card-text-en.json`, and the pin means a hand-written config is a config that
    stops validating the day `kz_config` gains a field. `koreanize_sandbox.Sandbox`
    already drives the real `init` to produce all three; `regrid()` below then
    rewrites the ONE thing `init` cannot produce offline -- a measured atlas --
    and re-pins. So the inputs are `init`'s own, not this file's idea of them.
"""

import json
import os
import shutil
import subprocess
import sys

import pytest

import kz_common as kc
import kz_slice as ks
import kz_config as kz

from tests.koreanize_sandbox import EN_FACE, Sandbox

SLICE_PY = os.path.join(kc.PACKAGE_DIR, "kz_slice.py")


# ---------------------------------------------------------------------------
# 0. The fixture: a real init run whose one atlas has been measured for us
# ---------------------------------------------------------------------------

def regrid(box, num_width, num_height, cell_w, cell_h, pixels=None, cells=None):
    """Give the sandbox's single English atlas a MEASURED geometry.

    `init` records `pixels: null` for any sheet it could not fetch, and the
    sandbox runs it with `download_atlases=False` because no test may reach the
    network -- so the one input `slice` cannot get from the real `init` here is
    the measurement. This plants it, consistently, in all three artifacts that
    carry it:

      * `<run_dir>/assets/<sha256>.png`, where `init` would have put the download
      * `atlas-inventory.json`, the record `slice` confirms against
      * `scenario.json`, re-pinned -- `config_sha256` is what stops a hand-edit
        silently retargeting the tool (`kz_config.validate`), and a fixture that
        skipped the re-pin would be testing the pin instead of the stage

    and it recomputes each object's `row`/`col` in `card-text-en.json`, because
    those are `divmod(cell, num_width)` and moving the grid moves them.

    `pixels` overrides the sheet's recorded dims WITHOUT changing the file, which
    is the only way to build the non-integral case: `synth_atlas` can only draw a
    sheet that divides.

    `cells` reassigns which cell each object sits in, and it exists because the
    sandbox's cards are authored against a 7x4 `CustomDeck` -- `init` itself
    refuses a `CardID` whose cell falls outside the grid it was written with
    (`kz_init.check_geometry`), so a 10x7 fixture cannot state its cells up front
    without making `init` refuse before this helper is ever reached. Assigning
    them AFTER `init` is what lets the same sandbox carry a 70-cell sheet, and
    `card_id` is recomputed with the cell so TTS's own `deck_key*100 + cell`
    round-trip still holds.
    """
    run_dir = box.run_dir
    # When `pixels` is given the SHEET is drawn at those dims and the grid is
    # declared independently of them -- which is the whole non-integral case:
    # `synth_atlas` can only ever draw a sheet that divides by the grid it is
    # given, so a fixture that drew `num_width x num_height` cells and then
    # relabelled the record would refuse at 14 (the file no longer matches the
    # measurement) before the integrality assertion was ever reached.
    if pixels:
        atlas_path = ks.synth_atlas(os.path.join(run_dir, "atlas-src.png"),
                                    1, 1, pixels[0], pixels[1])
    else:
        atlas_path = ks.synth_atlas(os.path.join(run_dir, "atlas-src.png"),
                                    num_width, num_height, cell_w, cell_h)
    digest = kc.sha256_file(atlas_path)
    assets = os.path.join(run_dir, "assets")
    if not os.path.isdir(assets):
        os.makedirs(assets)
    shutil.copyfile(atlas_path, os.path.join(assets, "%s.png" % digest))
    os.unlink(atlas_path)

    measured = list(pixels) if pixels else [num_width * cell_w, num_height * cell_h]
    record = {
        "atlas_id": digest[:16], "side": "face", "english_url": EN_FACE,
        "local": os.path.join("<run_dir>", "assets", "%s.png" % digest),
        "grid": {"num_width": num_width, "num_height": num_height},
        "pixels": measured,
        "cell_pixels": ([measured[0] // num_width, measured[1] // num_height]
                        if not (measured[0] % num_width or measured[1] % num_height)
                        else None),
        "bytes": os.path.getsize(os.path.join(assets, "%s.png" % digest)),
        "sha256": digest,
        "cells_used": 1, "packs": [],
        "single_card": bool(num_width == 1 and num_height == 1),
    }

    inventory_path = os.path.join(run_dir, "atlas-inventory.json")
    inventory = _read(inventory_path)
    inventory["atlases"] = [record]
    _write(inventory_path, inventory)

    scenario_path = os.path.join(run_dir, "scenario.json")
    cfg = _read(scenario_path)
    cfg["atlases"] = [record]
    cfg["config_sha256"] = kz.compute_config_sha256(cfg)
    _write(scenario_path, cfg)

    en_path = os.path.join(run_dir, "card-text-en.json")
    en_doc = _read(en_path)
    for obj in en_doc["objects"]:
        if obj.get("cell") is None:
            continue
        if cells is not None and obj.get("arkham_id") in cells:
            obj["cell"] = cells[obj["arkham_id"]]
            obj["card_id"] = int(obj["deck_key"]) * 100 + obj["cell"]
        obj["num_width"] = num_width
        obj["num_height"] = num_height
        obj["row"], obj["col"] = divmod(obj["cell"], num_width)
    _write(en_path, en_doc)

    box.cfg = cfg
    return record


def _read(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _write(path, data):
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(data, handle, indent=2, ensure_ascii=False)
        handle.write("\n")


def make_box(tmp_path, cards):
    """A sandbox with `cards` and no donors, through the real `init`.

    No donors and no `source()` run: `slice`'s only predecessor is `init`
    (`kz_config.PREDECESSORS`), and a fixture that ran more of the chain than the
    stage depends on would fail for reasons that are not this stage's.
    """
    box = Sandbox(tmp_path).build(cards=cards, donors={})
    box.init()
    return box


def atlas_file(box):
    inventory = _read(os.path.join(box.run_dir, "atlas-inventory.json"))
    digest = inventory["atlases"][0]["sha256"]
    return os.path.join(box.run_dir, "assets", "%s.png" % digest)


def slice_path(box, name):
    return os.path.join(box.run_dir, ks.SLICES_DIR, name)


# ---------------------------------------------------------------------------
# 1. Every --selftest fault as a pytest case (§2 item 40's rule, applied here)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("fault", ks.FAULTS)
def test_selftest_fault_passes(fault):
    """Each named fault, in-process, so a failure names the predicate."""
    assert ks.selftest(fault=fault, verbose=False) == []


def test_selftest_faults_are_total_over_the_predicates():
    """A predicate with no named fault is a predicate nobody runs.

    Asserted LITERALLY rather than derived from the module, for the reason §4.4
    gives the rule->fixture map: a set discovered from the code under test grows
    and shrinks silently with it.
    """
    assert ks.FAULTS == ("norm", "resolve", "integrality", "geometry",
                         "single-card", "reread", "guard")


def test_selftest_runs_as_a_subprocess_and_exits_zero():
    """The CLI path `koreanize.sh selftest` uses, not only the function."""
    proc = subprocess.run([sys.executable, SLICE_PY, "--selftest"],
                          capture_output=True, text=True)
    assert proc.returncode == kc.EXIT_OK, proc.stdout + proc.stderr
    for fault in ks.FAULTS:
        assert fault in proc.stdout


def test_unknown_fault_refuses_at_usage():
    with pytest.raises(kc.KzRefusal) as excinfo:
        ks.selftest(fault="no-such-fault", verbose=False)
    assert excinfo.value.code == kc.EXIT_USAGE


# ---------------------------------------------------------------------------
# 2. The constant table is gone, and `norm()` is not
# ---------------------------------------------------------------------------

def test_module_declares_no_cell_size_table():
    """R-A's structural mitigation, asserted on the source text.

    §5.4: "`slice-atlases.py:48-53`'s `EXPECTED_SHEET_DIMS` constant disappears."
    A cell size that can be looked up is a cell size somebody will look up, and
    the failure mode is silent -- a table hit for the wrong sheet crops plausible
    cards from the wrong offsets. The literal figures are searched for because
    they are the ones that would be reintroduced: 750x1050 is Midwinter's cell.
    """
    import ast

    with open(SLICE_PY, "r", encoding="utf-8") as handle:
        tree = ast.parse(handle.read(), filename=SLICE_PY)

    # Parsed and not grepped, because the module's own header QUOTES the legacy
    # constants in order to explain their deletion. A text scan cannot tell a
    # citation from a declaration, so it would either fail on the prose or be
    # weakened until it passed on a real one.
    assigned, literals = set(), set()
    for node in tree.body:
        targets = []
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
        else:
            continue
        for target in targets:
            if isinstance(target, ast.Name):
                assigned.add(target.id)
        for inner in ast.walk(node):
            if isinstance(inner, ast.Constant) and isinstance(inner.value, int):
                literals.add(inner.value)

    for banned in ("EXPECTED_SHEET_DIMS", "SHEET_DIMS", "CELL_W", "CELL_H",
                   "CELL_PIXELS", "CELL_SIZE"):
        assert banned not in assigned, "%s is back as a module constant" % banned

    # And no MODULE-LEVEL constant may carry the reference cell size as a literal
    # pair: 750x1050 is Midwinter's cell and is what a reintroduced table would
    # hold. Scoped to module level deliberately -- `--selftest integrality` plants
    # [750, 1050] as a fault fixture, and that is the opposite of a lookup table.
    assert not (750 in literals and 1050 in literals)


def test_norm_is_the_legacy_normalisation():
    """`slice-atlases.py:56-57`, kept. The suite asserts it against the regex
    form because "kept" has to be checkable: if these diverge, every file in
    `images-ko/assets/` becomes unreachable at once and with no diagnostic."""
    import re
    legacy = lambda s: re.sub(r"[^a-zA-Z0-9]", "", s).lower()  # noqa: E731
    for sample in ("https://steamusercontent-a.akamaihd.net/ugc/24078/C570E6/",
                   "", "Ab_9-/.", "MiXeD CaSe", "%20", "ünïcödé"):
        assert ks.norm(sample) == legacy(sample), sample


def test_url_stem_filenames_prefix_match_their_url():
    """The property the read-only tier's mapping rests on: `images-ko/assets/`
    names each download after its URL with the punctuation stripped, so the
    on-disk name is `norm(url)` plus an extension."""
    url = "https://steamusercontent-a.akamaihd.net/ugc/24078/C570E6/"
    assert ks.norm(url + ".png").startswith(ks.norm(url))
    assert ks.norm(ks.norm(url) + ".png").startswith(ks.norm(url))


# ---------------------------------------------------------------------------
# 3. (1,1) -- Woods of the Black Goat's shape. A COPY, not a crop.
# ---------------------------------------------------------------------------

def test_one_by_one_atlas_is_copied_byte_for_byte(tmp_path):
    """§5.4: "`single_card` atlases produce a copy, not a crop, and are recorded
    as such."

    Both halves are asserted, because either alone is satisfiable by the wrong
    implementation: a full-sheet `crop()` produces identical PIXELS and different
    BYTES, and a manifest can say `copy` about a re-encode. The byte identity is
    what keeps a Pillow upgrade out of §5.8's byte-exact golden comparison.
    """
    box = make_box(tmp_path, cards=[("111111", "01001", 10000)])
    record = regrid(box, 1, 1, 24, 32)

    report, manifest = ks.run_slice(box.run_dir, workspace=box.root)

    assert report["exit_code"] == kc.EXIT_OK, report["checks"]
    assert report["counts"]["atlases_single_card"] == 1
    assert report["counts"]["slices_copied"] == 1
    assert report["counts"]["slices_cropped"] == 0

    entry = manifest["records"][0]
    assert entry["operation"] == "copy"
    assert entry["cell_pixels"] == [24, 32]
    assert entry["sha256"] == record["sha256"]
    with open(slice_path(box, entry["filename"]), "rb") as emitted:
        with open(atlas_file(box), "rb") as source:
            assert emitted.read() == source.read()


def test_one_by_one_cell_pixels_are_the_whole_sheet(tmp_path):
    """The arithmetic, isolated from the emission: on a (1,1) sheet the derived
    cell IS the sheet, which is the case a constant table gets wrong by
    construction."""
    box = make_box(tmp_path, cards=[("111111", "01001", 10000)])
    record = regrid(box, 1, 1, 40, 55)
    assert ks.cell_pixels_for(record, measured=(40, 55)) == (40, 55)


# ---------------------------------------------------------------------------
# 4. (10,7) -- Labyrinths' shape. A crop, from the RIGHT cell.
# ---------------------------------------------------------------------------

#: The sandbox's own cards, authored against the 7x4 `CustomDeck` its `_card`
#: helper writes, so `init` accepts them; `regrid(cells=...)` then moves them
#: onto the 10x7 sheet. Cell 69 is deliberately the LAST cell of that grid, so
#: the crop box reaches the sheet's far corner exactly and an off-by-one in
#: either axis leaves the sheet instead of passing quietly.
TEN_BY_SEVEN = [("111111", "01001", 10001),
                ("222222", "01002", 10002),
                ("333333", "01003", 10003)]
TEN_CELLS = {"01001": 1, "01002": 10, "01003": 69}


def test_ten_by_seven_derives_the_cell_and_crops_each_card(tmp_path):
    """The 70-cell sheet no constant table in the repository describes.

    The last card is deliberately cell 69 -- the final cell of a 10x7 grid -- so
    the crop box reaches the sheet's far corner exactly. An off-by-one in either
    axis leaves the sheet and refuses at 20 rather than passing quietly.
    """
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)

    report, manifest = ks.run_slice(box.run_dir, workspace=box.root)

    assert report["exit_code"] == kc.EXIT_OK, report["checks"]
    assert report["counts"]["slices"] == 3
    assert report["counts"]["slices_cropped"] == 3
    assert report["counts"]["slices_copied"] == 0
    assert report["counts"]["atlases_single_card"] == 0

    cells = dict((r["arkham_id"], (r["cell"], r["row"], r["col"], tuple(r["box"])))
                 for r in manifest["records"])
    assert cells["01001"] == (1, 0, 1, (12, 0, 24, 16))
    assert cells["01002"] == (10, 1, 0, (0, 16, 12, 32))
    assert cells["01003"] == (69, 6, 9, (108, 96, 120, 112))
    for entry in manifest["records"]:
        assert entry["cell_pixels"] == [12, 16]


def test_ten_by_seven_slices_carry_the_pixels_of_their_own_cell(tmp_path):
    """THE case that catches a wrong-cell crop, which no dimension check can.

    Every emitted slice is compared against the crop taken independently from the
    source sheet at the box the manifest declares -- and `synth_atlas` paints a
    different colour per cell, so a slice cut one cell over is different bytes
    rather than the same picture. The three slices are also asserted PAIRWISE
    DISTINCT, because on a uniform sheet the comparison above passes for every
    permutation and establishes nothing.
    """
    from PIL import Image

    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    _report, manifest = ks.run_slice(box.run_dir, workspace=box.root)

    digests = set()
    with Image.open(atlas_file(box)) as sheet:
        rgba = sheet.convert("RGBA")
        for entry in manifest["records"]:
            expected = rgba.crop(tuple(entry["box"]))
            with Image.open(slice_path(box, entry["filename"])) as emitted:
                assert emitted.size == (12, 16)
                assert emitted.convert("RGBA").tobytes() == expected.tobytes(), \
                    entry["filename"]
            digests.add(entry["sha256"])
    assert len(digests) == 3, "the cells are indistinguishable, so this proves nothing"


def test_ten_by_seven_cell_pixels_are_derived_not_looked_up(tmp_path):
    """`(10,7)` at the reference cell size, through the arithmetic alone.

    750x1050 is Midwinter's cell and 10x7 is Carnevale's grid (§3.4), so this is
    the pair a reintroduced table would be written from. It is asserted here
    without drawing a 55 MP sheet, because the derivation does not need pixels.
    """
    record = {"english_url": "https://example.invalid/a.png",
              "grid": {"num_width": 10, "num_height": 7},
              "pixels": [7500, 7350], "cell_pixels": [750, 1050],
              "single_card": False}
    assert ks.cell_pixels_for(record, measured=(7500, 7350)) == (750, 1050)


# ---------------------------------------------------------------------------
# 5. The non-integral division -- it must refuse
# ---------------------------------------------------------------------------

def test_non_integral_division_refuses_at_precondition(tmp_path):
    """§6 step 11's third required case.

    A 100x100 sheet declared as a 7x4 grid has NO cell size: 100 % 7 == 2 and
    100 % 4 == 0, so one axis divides and the other does not. Exit 13 and not 20:
    nothing has been sliced wrongly, the INPUT cannot be sliced at all -- which
    is the same class and the same code `kz_init.measure_atlases` refuses the
    identical fact with, deliberately down to the message string.
    """
    box = make_box(tmp_path, cards=[("111111", "01001", 10001)])
    regrid(box, 7, 4, 10, 10, pixels=[100, 100])

    with pytest.raises(kc.KzRefusal) as excinfo:
        ks.run_slice(box.run_dir, workspace=box.root)

    assert excinfo.value.code == kc.EXIT_PRECONDITION
    assert "do not divide by its grid" in excinfo.value.message
    assert "100 % 7 = 2" in excinfo.value.detail


def test_non_integral_division_writes_nothing(tmp_path):
    """"Nothing was written" is the whole value of a precondition refusal.

    The assertion is on the filesystem and not on the message: a stage that
    refused after emitting half a directory would report the same code and leave
    a partial `slices/` for the next run to consume.
    """
    box = make_box(tmp_path, cards=[("111111", "01001", 10001)])
    regrid(box, 7, 4, 10, 10, pixels=[100, 100])

    with pytest.raises(kc.KzRefusal):
        ks.run_slice(box.run_dir, workspace=box.root)

    assert not os.path.exists(os.path.join(box.run_dir, ks.SLICES_DIR))
    assert not os.path.exists(os.path.join(box.run_dir, ks.GALLERY_DIR))
    assert not os.path.exists(kc.report_path(box.run_dir, "slice", "build"))


@pytest.mark.parametrize("pixels,grid", [
    ([100, 100], (7, 4)),      # neither axis divides cleanly on width
    ([100, 100], (2, 3)),      # width divides, height does not
    ([101, 100], (1, 1)),      # a (1,1) sheet always divides -- see below
])
def test_non_integral_cases(pixels, grid):
    """The refusal is per axis, not per sheet.

    The third row is the one that earns its place: on a `(1,1)` grid EVERY
    dimension divides, so the integrality assertion is vacuous there and the
    `single_card` path can never reach it. Stating that here stops a future
    "optimise: skip the check for single_card" edit from reading as a change in
    behaviour when it is not.
    """
    record = {"english_url": "https://example.invalid/a.png",
              "grid": {"num_width": grid[0], "num_height": grid[1]},
              "pixels": pixels, "cell_pixels": None,
              "single_card": bool(grid == (1, 1))}
    if grid == (1, 1):
        assert ks.cell_pixels_for(record) == tuple(pixels)
        return
    with pytest.raises(kc.KzRefusal) as excinfo:
        ks.cell_pixels_for(record)
    assert excinfo.value.code == kc.EXIT_PRECONDITION


# ---------------------------------------------------------------------------
# 6. Per-file sha256, the manifest, and the contact sheet
# ---------------------------------------------------------------------------

def test_every_slice_carries_a_sha256_that_matches_disk(tmp_path):
    """§6 step 11: "per-file sha256". §5.11 clause (e) asserts an assembled
    package against these digests, so a recorded digest that does not match the
    file is a package assertion that passes on the wrong bytes."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    _report, manifest = ks.run_slice(box.run_dir, workspace=box.root)

    for entry in manifest["records"]:
        path = slice_path(box, entry["filename"])
        assert len(entry["sha256"]) == 64
        assert entry["sha256"] == kc.sha256_file(path)
        assert entry["bytes"] == os.path.getsize(path)


def test_manifest_describes_exactly_the_directory(tmp_path):
    """Set equality in both directions (SL8). A file in `slices/` the manifest
    does not name is a file that would ship undeclared."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    _report, manifest = ks.run_slice(box.run_dir, workspace=box.root)

    on_disk = set(os.listdir(os.path.join(box.run_dir, ks.SLICES_DIR)))
    on_disk.discard(ks.MANIFEST_NAME)
    assert on_disk == set(r["filename"] for r in manifest["records"])

    stray = slice_path(box, "undeclared.png")
    shutil.copyfile(slice_path(box, manifest["records"][0]["filename"]), stray)
    checks, triggered = ks.verify_emitted(manifest["records"], box.run_dir)
    sl8 = [c for c in checks if c["id"] == "SL8"][0]
    assert sl8["status"] == "fail"
    assert kc.EXIT_RULE_B in triggered


def test_contact_sheet_is_written_and_names_every_slice(tmp_path):
    """The human review surface. It is not gated here -- `slice` is not one of
    §3.2's four gated stages -- but it is the surface the `mask` gate reads, and
    a gallery that omits a slice is a review nobody performed on it."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    report, manifest = ks.run_slice(box.run_dir, workspace=box.root)

    path = os.path.join(box.run_dir, ks.GALLERY_DIR, ks.CONTACT_SHEET_NAME)
    assert os.path.exists(path)
    with open(path, "r", encoding="utf-8") as handle:
        html = handle.read()
    for entry in manifest["records"]:
        assert entry["filename"] in html
        assert str(entry["cell"]) in html
        assert entry["arkham_id"] in html
    # Self-contained but for the sibling PNGs. The atlas URL appears as TEXT --
    # a reviewer has to see which sheet a section came off -- so the assertion is
    # about what the page would FETCH, not about what it prints.
    assert "<script" not in html and "<link" not in html and "@import" not in html
    assert html.count("<img") == len(manifest["records"])
    assert html.count('src="../%s/' % ks.SLICES_DIR) == len(manifest["records"])
    assert report["results"]["contact_sheet"].endswith(ks.CONTACT_SHEET_NAME)


def test_report_gate_is_null_so_nothing_waits_on_a_human(tmp_path):
    """`slice` is absent from §3.2's `gates` block, so a gate record here would
    make the report permanently non-consumable on a review nobody was asked
    for."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    report, _manifest = ks.run_slice(box.run_dir, workspace=box.root)
    assert "slice" not in (box.cfg.get("gates") or {})
    assert report["gate"] is None
    assert report["consumable"] is True, report["consumable_blocked_by"]


# ---------------------------------------------------------------------------
# 7. The forbidden-AI contract (§3.2, §5.4)
# ---------------------------------------------------------------------------

def test_slice_is_declared_forbidden_ai_in_the_module_body():
    assert kc.AI_CONTRACT["slice"] is False
    assert "slice" in kz.PREDECESSORS
    assert kz.PREDECESSORS["slice"] == ("init",)


def test_report_carries_no_ai_block(tmp_path):
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    report, _manifest = ks.run_slice(box.run_dir, workspace=box.root)
    assert report["ai"] is None
    assert report["seed"] is None
    assert report["write_set"] is None
    assert report["registration"] is None


def test_a_build_report_with_an_ai_block_is_refused_at_the_guard(tmp_path):
    """The enforcement half, exercised rather than trusted.

    `kc.write_report` calls `assert_ai_contract` before the write, so an
    AI-influenced `slice` artifact cannot reach disk -- but the module also has
    to be in `ai.forbidden_stages` for that to fire, which is what this asserts
    against the sandbox's own generated config.
    """
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    report, _manifest = ks.run_slice(box.run_dir, workspace=box.root)

    assert "slice" in box.cfg["ai"]["forbidden_stages"]
    report["ai"] = {"used": True, "stage_id": "S9", "decide_outcome": "proceed"}
    with pytest.raises(kc.KzRefusal) as excinfo:
        kc.write_report(report, box.run_dir, cfg=box.cfg)
    assert excinfo.value.code == kc.EXIT_GUARD


# ---------------------------------------------------------------------------
# 8. The path guard -- writes stay inside <run_dir>
# ---------------------------------------------------------------------------

def _tree(root):
    out = {}
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            path = os.path.join(dirpath, name)
            out[path] = os.path.getmtime(path)
    return out


def test_nothing_outside_the_run_dir_is_touched(tmp_path):
    """§4.1's `writes outside <run_dir>: no` column, asserted on the filesystem.

    The subject is the sandbox's whole SCED-downloads tree, because that is what
    a mis-scoped write root would reach -- and it is a directory `slice` has no
    business opening even for reading.
    """
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    downloads = os.path.join(box.root, "SCED-downloads")
    before = _tree(downloads)

    ks.run_slice(box.run_dir, workspace=box.root)

    assert _tree(downloads) == before


def test_a_run_dir_inside_the_langpack_refuses_at_the_guard(tmp_path):
    """`--run-dir` is argv (§3.1), so it is NOT covered by `config_sha256` -- it
    is the one input to this stage a typo can retarget. The guard is what stops
    an ungated stage writing PNGs into SCED-downloads."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    target = os.path.join(box.root, box.cfg["guard"]["write_roots"][0])
    with pytest.raises(kc.KzRefusal) as excinfo:
        ks.assert_run_dir_writes(
            box.cfg, target,
            [os.path.join(target, ks.SLICES_DIR, "01001.png")],
            workspace=box.root)
    assert excinfo.value.code == kc.EXIT_GUARD
    assert "guard.write_roots" in excinfo.value.detail


def test_dry_run_writes_only_into_the_scratch_root(tmp_path):
    """§4.1: every stage's `--dry-run` output goes to `<run_dir>/dry-run/<stage>/`,
    asserted by `kz_config.assert_dry_run_dest` before the first byte."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)

    report, manifest = ks.run_slice(box.run_dir, mode="dry-run", workspace=box.root)

    scratch = os.path.join(box.run_dir, "dry-run", "slice")
    assert report["mode"] == "dry-run"
    assert os.path.isdir(os.path.join(scratch, ks.SLICES_DIR))
    assert not os.path.exists(os.path.join(box.run_dir, ks.SLICES_DIR))
    for entry in manifest["records"]:
        assert os.path.exists(os.path.join(scratch, ks.SLICES_DIR, entry["filename"]))
    # A rehearsal is never consumable, so nothing downstream can read it.
    assert report["consumable"] is False


# ---------------------------------------------------------------------------
# 9. Re-reading from disk -- and verify-only
# ---------------------------------------------------------------------------

def test_verify_only_catches_a_slice_replaced_after_the_build(tmp_path):
    """The re-read is not ceremony: it is the only thing that sees a file
    replaced between the write and the read. `--verify-only` reads the records
    from the manifest ON DISK rather than from a fresh plan, because verifying a
    plan against itself establishes nothing about the files a previous run
    left."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    _report, manifest = ks.run_slice(box.run_dir, workspace=box.root)

    clean, _ = ks.run_slice(box.run_dir, mode="verify-only", workspace=box.root)
    assert clean["exit_code"] == kc.EXIT_OK, clean["checks"]

    victim = slice_path(box, manifest["records"][0]["filename"])
    with open(victim, "wb") as handle:
        handle.write(b"\x89PNG not really")

    tampered, _ = ks.run_slice(box.run_dir, mode="verify-only", workspace=box.root)
    assert tampered["exit_code"] == kc.EXIT_RULE_B
    sl7 = [c for c in tampered["checks"] if c["id"] == "SL7"][0]
    assert sl7["status"] == "fail"
    assert manifest["records"][0]["filename"] in " ".join(sl7["detail"])


def test_verify_only_writes_no_pixels_and_its_own_report_suffix(tmp_path):
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    ks.run_slice(box.run_dir, workspace=box.root)
    before = _tree(os.path.join(box.run_dir, ks.SLICES_DIR))

    report, _ = ks.run_slice(box.run_dir, mode="verify-only", workspace=box.root)
    assert _tree(os.path.join(box.run_dir, ks.SLICES_DIR)) == before
    assert kc.report_path(box.run_dir, "slice", "verify-only").endswith(
        "slice.verify.json")
    assert report["consumable"] is False


# ---------------------------------------------------------------------------
# 10. Atlas resolution -- content address first, norm() as the fallback
# ---------------------------------------------------------------------------

def test_content_addressed_asset_is_preferred_over_the_url_stem_root(tmp_path):
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    record = regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    found = ks.resolve_atlas_file(record, box.run_dir, [tmp_path])
    assert found["how"] == "content-address"
    assert found["path"] == atlas_file(box)


def test_url_normalisation_resolves_from_a_named_root(tmp_path):
    """The read-only tier's path (§3.1). With the content-addressed copy gone,
    `norm()` is the ONLY way back from a `FaceURL` to `images-ko/assets/`."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    record = regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)

    root = os.path.join(str(tmp_path), "images-ko", "assets")
    os.makedirs(root)
    shutil.move(atlas_file(box), os.path.join(root, ks.norm(EN_FACE) + ".png"))

    found = ks.resolve_atlas_file(record, box.run_dir, [root])
    assert found["how"] == "url-normalisation"

    report, manifest = ks.run_slice(box.run_dir, workspace=box.root,
                                    atlas_root=[root])
    assert report["exit_code"] == kc.EXIT_OK
    assert manifest["atlas_mapping"][0]["resolved_by"] == "url-normalisation"


def test_a_missing_atlas_refuses_at_precondition(tmp_path):
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    os.unlink(atlas_file(box))
    with pytest.raises(kc.KzRefusal) as excinfo:
        ks.run_slice(box.run_dir, workspace=box.root)
    assert excinfo.value.code == kc.EXIT_PRECONDITION


def test_an_atlas_whose_bytes_moved_refuses_as_drift(tmp_path):
    """Missing is 13, moved is 14, and the two need different first moves: fetch
    it, versus find out who rewrote it."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    # Same path, same dims, different pixels -- so only the digest can see it.
    ks.synth_atlas(atlas_file(box), 10, 7, 12, 16)
    with open(atlas_file(box), "ab") as handle:
        handle.write(b"\n")
    with pytest.raises(kc.KzRefusal) as excinfo:
        ks.run_slice(box.run_dir, workspace=box.root)
    assert excinfo.value.code == kc.EXIT_DRIFT


# ---------------------------------------------------------------------------
# 11. The report envelope
# ---------------------------------------------------------------------------

def test_report_binds_its_three_inputs_and_names_init_upstream(tmp_path):
    """`binding{}` is the whole staleness mechanism (`kz_config.stage_state`): a
    rebuild of any input invalidates this stage without anyone remembering to."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    report, _ = ks.run_slice(box.run_dir, workspace=box.root)

    bound = set(os.path.basename(p) for p in report["binding"])
    assert bound == {"scenario.json", "atlas-inventory.json", "card-text-en.json"}
    assert report["freshness"]["upstream_report"].endswith("init.json")
    assert report["tool"]["pil"] is not None
    assert report["stage"] == "slice"


def test_stage_state_reads_the_report_and_sees_it_go_stale(tmp_path):
    """The report is only useful if `--status` can read it, and `stale` is what
    makes a re-run of `init` invalidate this stage."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    report, _ = ks.run_slice(box.run_dir, workspace=box.root)
    kc.write_report(report, box.run_dir, cfg=box.cfg)

    state = kz.stage_state(box.run_dir, "slice", workspace=box.root)
    assert state["present"] and state["consumable"] and not state["stale"]

    en_path = os.path.join(box.run_dir, "card-text-en.json")
    doc = _read(en_path)
    doc["counts"]["touched"] = 1
    _write(en_path, doc)

    state = kz.stage_state(box.run_dir, "slice", workspace=box.root)
    assert state["stale"] is True
    assert any(p.endswith("card-text-en.json") for p in state["stale_paths"])


def test_checks_are_total_over_both_bands(tmp_path):
    """SL1-SL5 are the preflight's assertions recorded as passes; SL6-SL8 are
    evaluated after the write. A report carrying only the second half would be
    one an operator has to know the module's internals to read."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    report, _ = ks.run_slice(box.run_dir, workspace=box.root)

    ids = [c["id"] for c in report["checks"]]
    assert ids == ["SL1", "SL2", "SL3", "SL4", "SL6", "SL7", "SL8"]
    for check in report["checks"]:
        assert check["exit_on_fail"] in kc.EXIT_PRECEDENCE
        assert check["status"] == "pass"


# ---------------------------------------------------------------------------
# 12. Objects with no cell, and the shared backs
# ---------------------------------------------------------------------------

def test_an_object_with_no_cell_is_skipped_and_counted(tmp_path):
    """The scenario guide is a `Custom_PDF` with no `CustomDeck` at all
    (`kz_init.check_geometry`), so refusing on it would refuse both reference
    corpora at the first art stage."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)

    en_path = os.path.join(box.run_dir, "card-text-en.json")
    doc = _read(en_path)
    doc["objects"].append({
        "guid": "pdf001", "object_id": "Root/Guide.pdf001", "arkham_id": None,
        "kind": "Custom_PDF", "card_id": None, "deck_key": None,
        "cell": None, "row": None, "col": None,
        "atlas_id": None, "back_atlas_id": None,
        "num_width": None, "num_height": None, "pack": None,
        "nickname": "Scenario Guide", "description": "", "source_file": "g.json"})
    _write(en_path, doc)

    report, manifest = ks.run_slice(box.run_dir, workspace=box.root)
    assert report["exit_code"] == kc.EXIT_OK
    assert report["counts"]["objects_without_cell"] == 1
    assert report["counts"]["slices"] == 3
    assert all(r["guid"] != "pdf001" for r in manifest["records"])


def test_shared_backs_are_counted_and_not_sliced(tmp_path):
    """`init` measures FACE atlases only (`kz_init.collect_atlas_urls` records a
    back as a bare occurrence count with no grid), so there is no geometry to cut
    a back with. It is counted and named rather than silently absent."""
    box = make_box(tmp_path, cards=TEN_BY_SEVEN)
    regrid(box, 10, 7, 12, 16, cells=TEN_CELLS)
    inventory = _read(os.path.join(box.run_dir, "atlas-inventory.json"))
    assert inventory["shared_backs"], "the fixture has no shared back to count"

    report, manifest = ks.run_slice(box.run_dir, workspace=box.root)
    assert report["counts"]["shared_backs_not_sliced"] == len(
        inventory["shared_backs"])
    assert all(r["side"] == "face" for r in manifest["records"])
