#!/usr/bin/env python3
"""
Build an offline per-card image-atlas index for the Korean langpack, and
(opt-in) the authoritative Korean image-language coverage report.

Reads the decomposed TTS card JSON directly from
``SCED-downloads/decomposed/language-pack/Korean - */`` (approach A2) and emits,
for each object, which atlas image (front + back) it uses and where the card
sits within the atlas grid (``cell_index``, ``x``, ``y``). Deliverable A only:
no image cropping, no network access, no atlas-dimension fetching.

Reading decomposed JSON is what makes the index correct: each file isolates
exactly one deck, so no wrong-deck grid can be joined — unlike the packed
catalog, which mis-joined grids for 3 promo cards.

Coverage mode (``--coverage``) additionally assigns every object an
**image-language verdict derived from the host of the image URL it actually
points at** (R2 -> korean, Steam -> english, anything else -> unknown), rolls
those verdicts up per content unit, and writes ``korean_coverage_report.json``
/ ``.csv``.

SUPERSEDES, for judging whether Korean langpack content renders Korean art:
``SCED-downloads/misc/localization_reports/Korean_report.json`` (generated by
``SCED-downloads/misc/language-pack-completion-stats.py``). That metric decides
coverage by GMNotes-id set membership and reads no image URL, so an object
carrying the right id while pointing at the English Steam host scores as
covered there. It is NOT superseded for its inventory of ids required but
absent from the Korean tree — this script never reads the English base tree.
See ``SCED-tools/docs/korean-coverage-metric.md``.

Output under ``output/korean-player-card-index/`` (index) or
``output/korean-coverage-metric/`` (``--coverage``):
  - korean_card_index.csv        (1 row per card, 23 columns, RFC-4180 quoting)
  - korean_card_index.json       (structured record array + counts + anomalies)
  - korean_coverage_report.json  (--coverage only; per-unit + global rollup)
  - korean_coverage_report.csv   (--coverage only; 1 row per unit, 15 columns)
  - manifest.json                (run metadata, counts, anomalies, sha256)

Usage:
  build-korean-card-index.py
    [--source-dir PATH | --packs LIST] [--decomposed-root PATH]
    [--coverage] [--incumbent-report PATH]
    [--out-dir PATH] [--pretty] [--dry-run]

Exit codes:
  0  OK: no anomalies AND no count-reconciliation drift
  1  warnings: one or more row-level anomalies, OR count drift
     (json_files_scanned != cards_written), OR an unreadable
     --incumbent-report. Non-fatal — outputs still written.
     Exit 1 is the ORDINARY outcome of `--packs all --coverage`: the tree
     carries anomalies that are recorded rather than fatal. Do not read it
     as a failed run, and do not expect any particular anomaly count.
  40 GMNotes invariant violation (missing / empty / non-JSON / missing 'id').
     STRICT MODE ONLY. Under --coverage this is demoted to the row anomaly
     gmnotes_unresolved (or gmnotes_sidecar_resolved when GMNotes_path
     resolves).
  41 grid invariant violation (NumWidth/NumHeight not losslessly int-coercible)
  42 sha256 mismatch on write-back verification
  43 missing source/pack dir, or a card with empty CustomDeck.
     The empty-CustomDeck half is STRICT MODE ONLY. Under --coverage it is
     demoted to the row anomaly no_custom_deck. The missing-dir half is
     unconditional and also fires for a --packs entry whose directory is
     absent.
   2 argparse usage error (e.g. --source-dir with --packs, or
     --incumbent-report without --coverage)
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import re
import sys
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from urllib.parse import urlparse

SCRIPTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPTS_DIR.parent.parent
SCED_DOWNLOADS_PATH = REPO_ROOT / "SCED-downloads"
DEFAULT_DECOMPOSED_ROOT = SCED_DOWNLOADS_PATH / "decomposed"

SOURCE_SUBPATH = (
    "language-pack/Korean - Player Cards/Korean-PlayerCards.KoreanI"
)
DEFAULT_SOURCE_DIR = DEFAULT_DECOMPOSED_ROOT / SOURCE_SUBPATH
DEFAULT_OUTPUT = SCRIPTS_DIR / "output" / "korean-player-card-index"
DEFAULT_OUTPUT_COVERAGE = SCRIPTS_DIR / "output" / "korean-coverage-metric"

SCHEMA_VERSION = "1.0.0"
COVERAGE_SCHEMA_VERSION = "1.0.0"
COVERAGE_REPORT_KIND = "korean_image_language_coverage"
INDEXER_SCRIPT = "build-korean-card-index.py"
PACK = "playercards"

# Pack registry (design §5.1). Generalises extract-korean-atlases.py's
# hardcoded category 2-tuple into a registry; iteration order is insertion
# order and is what makes the multi-pack sort key a total order.
PACKS = {
    "playercards": SOURCE_SUBPATH,
    "campaigns": "language-pack/Korean - Campaigns/Korean-Campaigns.KoreanC",
    "fancampaigns": (
        "language-pack/Korean - Fan Campaigns/Korean-FanCampaigns.KoreanFC"
    ),
}
UNIT_KEY_SOURCE = {
    "playercards": "id_prefix",
    "campaigns": "directory",
    "fancampaigns": "directory",
}

# Image-language verdicts and the host map that produces them.
LANG_KOREAN = "korean"
LANG_ENGLISH = "english"
LANG_UNKNOWN = "unknown"
HOST_LANGUAGE = {"R2": LANG_KOREAN, "Steam": LANG_ENGLISH}

DOC_POINTER = "SCED-tools/docs/korean-coverage-metric.md"
INCUMBENT_ARTIFACT = (
    "SCED-downloads/misc/localization_reports/Korean_report.json"
)
INCUMBENT_GENERATOR = "SCED-downloads/misc/language-pack-completion-stats.py"

# Host fragments (copied verbatim from extract-korean-atlases.py).
R2_HOST_FRAGMENT = "pub-05b4fa32b44341d797f5c66d59384724.r2.dev"
STEAM_HOST_FRAGMENT = "steamusercontent-a.akamaihd.net"

# Fixed CSV column order (23 columns) — see design §3.
CSV_HEADER = [
    "name", "arkham_id", "card_id", "deck_key",
    "face_url", "face_source", "face_num_width", "face_num_height",
    "face_cell_index", "face_x", "face_y",
    "back_url", "back_source", "back_num_width", "back_num_height",
    "back_cell_index", "back_x", "back_y",
    "unique_back", "sideways", "pack",
    "source_file", "anomaly",
]

# Fixed coverage CSV column order (15 columns) — see design §3.2.
COVERAGE_CSV_HEADER = [
    "unit_key", "pack", "unit", "unit_key_source",
    "objects", "korean", "english", "unknown",
    "denominator", "korean_pct",
    "back_korean", "back_english", "back_unknown",
    "face_back_mismatch", "anomalies",
]

# Row-level anomaly codes (fixed set).
ANOMALY_CARD_ID_INVALID = "card_id_invalid"
ANOMALY_CELL_OUT_OF_BOUNDS = "cell_out_of_bounds"
ANOMALY_DECKKEY_MISMATCH = "deckkey_mismatch"
ANOMALY_MULTI_DECK = "multi_deck"
# Tolerant-mode-only codes: these shapes are hard exits 40/43 in strict mode.
ANOMALY_GMNOTES_SIDECAR_RESOLVED = "gmnotes_sidecar_resolved"
ANOMALY_GMNOTES_UNRESOLVED = "gmnotes_unresolved"
ANOMALY_NO_CUSTOM_DECK = "no_custom_deck"


def parse_args(argv=None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Build an offline per-card image-atlas index for "
                    "the Korean langpack, and (--coverage) the authoritative "
                    "Korean image-language coverage report.",
        epilog="Coverage supersedes Korean_report.json for judging whether "
               "Korean content renders Korean art; see " + DOC_POINTER + ".",
    )
    scope = p.add_mutually_exclusive_group()
    scope.add_argument("--source-dir", type=Path, default=None,
                       help="Walk exactly this directory as a single pack "
                            "labelled 'playercards'. Default: the decomposed "
                            "Korean Player Cards directory. Mutually "
                            "exclusive with --packs.")
    scope.add_argument("--packs", default=None,
                       help="Comma-separated subset of "
                            + ",".join(PACKS) + ", or 'all'. Each is "
                            "resolved against --decomposed-root. Mutually "
                            "exclusive with --source-dir.")
    p.add_argument("--decomposed-root", type=Path,
                   default=DEFAULT_DECOMPOSED_ROOT,
                   help="Root the --packs entries are resolved against "
                        "(default: SCED-downloads/decomposed). Relocation / "
                        "test hook only; ignored by --source-dir.")
    p.add_argument("--coverage", action="store_true",
                   help="Two effects: (1) tolerant object resolution — the "
                        "GMNotes (40) and empty-CustomDeck (43) hard exits "
                        "become row anomalies and Custom_PDF objects enter "
                        "scope; (2) emit korean_coverage_report.json + .csv.")
    p.add_argument("--incumbent-report", type=Path, default=None,
                   help="READ the named Korean_report.json to populate "
                        "incumbent_comparison. Never imports, executes or "
                        "writes anything from SCED-downloads/misc/. "
                        "Requires --coverage.")
    p.add_argument("--out-dir", type=Path, default=None,
                   help="Output directory for the index + manifest. Default: "
                        "output/korean-coverage-metric under --coverage, "
                        "else output/korean-player-card-index.")
    p.add_argument("--pretty", action="store_true",
                   help="No-op alias retained for parity (JSON is already "
                        "indent=2). Does not affect CSV or manifest bytes.")
    p.add_argument("--dry-run", action="store_true",
                   help="Compute everything but write no files; return the "
                        "would-be 0/1 exit code.")
    args = p.parse_args(argv)

    # --incumbent-report requires --coverage. argparse has no native
    # "requires" relation, so this post-parse check is what produces exit 2.
    if args.incumbent_report is not None and not args.coverage:
        p.error("--incumbent-report requires --coverage")

    # Resolve the walk scope into an ordered list of (pack, pack_root) pairs.
    if args.packs is not None:
        names = [s.strip() for s in args.packs.split(",") if s.strip()]
        if not names:
            p.error("--packs requires at least one pack name")
        if "all" in names:
            names = list(PACKS)
        unknown = [n for n in names if n not in PACKS]
        if unknown:
            p.error(
                "unknown --packs entries: %s (valid: %s, or 'all')"
                % (",".join(unknown), ",".join(PACKS))
            )
        selected = [n for n in PACKS if n in set(names)]
        root: Path = args.decomposed_root
        args.pack_pairs = [(n, root / PACKS[n]) for n in selected]
        args.single_pack_default = False
    else:
        source_dir = (
            DEFAULT_SOURCE_DIR if args.source_dir is None else args.source_dir
        )
        args.pack_pairs = [(PACK, source_dir)]
        args.single_pack_default = True

    if args.out_dir is None:
        args.out_dir = (
            DEFAULT_OUTPUT_COVERAGE if args.coverage else DEFAULT_OUTPUT
        )
    return args


def _resolve_gmnotes_sidecar(obj: dict, path: Path, pack_root: Path) -> str:
    """Resolve an id from an external ``.gmnotes`` sidecar; "" on miss.

    Lifts korean-image-audit.py:166-201 (the only script that already handles
    both GMNotes shapes) and hardens it with a containment guard the precedent
    lacks: ``GMNotes_path`` is attacker-influenceable data in a file the fork
    syncs from upstream, so a candidate resolving outside the pack root's
    parent is refused rather than read. Candidate order (design §5.3(ii)):

    1. the sibling ``<stem>.gmnotes`` — the one real case in this tree;
    2. ``pack_root.parent / GMNotes_path`` — the measured anchor;
    3. ``pack_root / GMNotes_path`` with the leading pack-root name stripped.
    """
    gm_path = obj.get("GMNotes_path")
    candidates = [path.parent / (path.stem + ".gmnotes")]
    if isinstance(gm_path, str) and gm_path:
        normalized = gm_path.replace("\\", "/")
        candidates.append(pack_root.parent / normalized)
        prefix = pack_root.name + "/"
        if normalized.startswith(prefix):
            candidates.append(pack_root / normalized[len(prefix):])

    try:
        boundary = pack_root.parent.resolve()
    except OSError:
        return ""

    for cand in candidates:
        try:
            resolved = cand.resolve()
        except OSError:
            continue
        if boundary != resolved and boundary not in resolved.parents:
            print(
                f"GMNotes sidecar refused (outside {boundary}): {resolved}",
                file=sys.stderr,
            )
            continue
        try:
            if not resolved.is_file():
                continue
            text = resolved.read_text(encoding="utf-8")
        except OSError:
            continue
        try:
            gm = json.loads(text)
        except (json.JSONDecodeError, ValueError):
            continue
        if isinstance(gm, dict) and gm.get("id") is not None:
            print(
                f"GMNotes resolved from sidecar: {path} -> {resolved.name}",
                file=sys.stderr,
            )
            return str(gm["id"])
    return ""


def _parse_gmnotes_id(
    obj: dict,
    location: str,
    tolerant: bool = False,
    path: Path = None,
    pack_root: Path = None,
) -> tuple:
    """Parse GMNotes (string or dict) and return ``(id, anomaly_code)``.

    Reuses the invariant pattern from build-candidates-index.py.

    Strict mode (the default, and today's behaviour) hard-exits 40 on any of
    the four violation shapes. Tolerant mode (``--coverage``) first attempts
    sidecar resolution and then returns ``("", gmnotes_unresolved)`` instead of
    exiting, so one unparseable object out of thousands cannot abort a
    coverage walk.
    """
    def violation(reason: str) -> tuple:
        if not tolerant:
            print(
                f"GMNotes invariant violation: {reason} at {location} "
                f"(--coverage records this as a row anomaly instead)",
                file=sys.stderr,
            )
            sys.exit(40)
        resolved = ""
        if path is not None and pack_root is not None:
            resolved = _resolve_gmnotes_sidecar(obj, path, pack_root)
        if resolved:
            return resolved, ANOMALY_GMNOTES_SIDECAR_RESOLVED
        print(
            f"GMNotes unresolved ({reason}) at {location}",
            file=sys.stderr,
        )
        return "", ANOMALY_GMNOTES_UNRESOLVED

    raw = obj.get("GMNotes", "")
    if isinstance(raw, dict):
        gm = raw
    elif isinstance(raw, str):
        if not raw.strip():
            return violation("empty GMNotes")
        try:
            gm = json.loads(raw)
        except json.JSONDecodeError:
            return violation("non-JSON GMNotes")
    else:
        return violation("unexpected type")
    if not isinstance(gm, dict) or "id" not in gm:
        return violation("missing 'id' key")
    return str(gm["id"]), ""


def _coerce_int(value, location: str, field: str) -> int:
    """Coerce CustomDeck NumWidth/NumHeight to int (R4 mitigation).

    TTSModManager normalization may emit floats — accept ints/floats convertible
    to int losslessly. Anything else is an invariant violation.
    """
    if isinstance(value, bool):
        # bools are ints in Python; treat as invariant violation explicitly.
        print(
            f"Grid invariant violation: bool value for {field} at {location}",
            file=sys.stderr,
        )
        sys.exit(41)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        if not math.isfinite(value):
            # NaN / +-Infinity (json.load accepts these tokens) is not coercible
            # to int — fail cleanly with the grid invariant code, not a traceback.
            print(
                f"Grid invariant violation: non-finite {field}={value!r} at {location}",
                file=sys.stderr,
            )
            sys.exit(41)
        coerced = int(value)
        if float(coerced) != value:
            print(
                f"Grid invariant violation: non-integral {field}={value!r} at {location}",
                file=sys.stderr,
            )
            sys.exit(41)
        return coerced
    print(
        f"Grid invariant violation: non-numeric {field}={value!r} at {location}",
        file=sys.stderr,
    )
    sys.exit(41)


def _coerce_card_id(value) -> int | None:
    """Soft-coerce a CardID to int; return None on any invalid value.

    Unlike the grid _coerce_int (hard exit 41), this never exits: CardID is the
    row's own primary key and the inventory philosophy is keep-and-flag, not
    crash (design §5.3). A None result means anomaly=card_id_invalid: the cell
    math and the deckkey_mismatch check are both skipped, the row is kept, and
    the run contributes to exit 1. Invalid = missing / null / bool /
    non-integral float / non-numeric.
    """
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        if not math.isfinite(value):
            # NaN / +-Infinity (json.load accepts these tokens): not a usable
            # CardID — keep-and-flag (return None), never crash on int(nan)/int(inf).
            return None
        coerced = int(value)
        if float(coerced) != value:
            return None
        return coerced
    return None


def classify_host(url: str) -> str:
    """Classify an atlas image URL host as a total enum: R2 | Steam | other.

    Applied independently to face_url and back_url (DRY within this script).

    # TODO(host-classifier-unification): single shared classify_host across
    # this script and extract-korean-atlases.py — see design §3/§5.9
    """
    if R2_HOST_FRAGMENT in url:
        return "R2"
    if STEAM_HOST_FRAGMENT in url:
        return "Steam"
    return "other"


def resolve_image_source(obj: dict, custom_deck_entry) -> tuple:
    """Return ``(url, field_label)`` for the object's FACE image.

    Shape-driven, never guessed: a Custom_PDF carries its image in
    ``CustomPDF.PDFUrl`` and has no CustomDeck at all; a card carries it in the
    selected ``CustomDeck`` entry's ``FaceURL``. ``custom_deck_entry is None``
    is the empty-CustomDeck signal from build_card_record (design §5.3(iii)).
    """
    if obj.get("Name") == "Custom_PDF":
        return (obj.get("CustomPDF") or {}).get("PDFUrl", ""), "CustomPDF.PDFUrl"
    if custom_deck_entry is not None:
        return custom_deck_entry.get("FaceURL", ""), "CustomDeck.FaceURL"
    return "", "none"


def image_language(url: str) -> str:
    """Adapt classify_host()'s three-valued host enum to a language verdict.

    A thin, separately-testable adapter rather than a second classifier, so
    the TODO(host-classifier-unification) path stays open: a future shared
    classifier only has to preserve classify_host's three-valued contract.
    """
    if not url:
        return LANG_UNKNOWN
    return HOST_LANGUAGE.get(classify_host(url), LANG_UNKNOWN)


def unknown_host_label(url: str) -> str:
    """Bucket label for the unknown_breakdown map."""
    if not url:
        return "(absent)"
    try:
        host = urlparse(url).hostname or ""
    except ValueError:
        host = ""
    if not host:
        return "(relative)"
    return host


def derive_unit_key(pack: str, source_file: str, arkham_id: str) -> str:
    """Derive ``<pack>/<unit>`` for the coverage rollup (design §3.5).

    ``campaigns``/``fancampaigns`` use the first path component (the campaign
    directory), falling back to the file stem for objects sitting directly at
    the pack root. ``playercards`` is flat — the directory rule would put
    1,859 of 2,136 objects in one bucket — so it uses the two-digit id prefix
    as a derived ``cycle-NN``. ``unit_key_source`` is emitted on every row so
    a derived cycle bucket is never mistaken for a real directory.

    Separator-normalised at construction via PurePosixPath, never patched
    afterwards, so the value is always '/' and never '\\'.
    """
    if UNIT_KEY_SOURCE.get(pack, "directory") == "id_prefix":
        if re.match(r"^\d{2}\d{3}", arkham_id or ""):
            unit = "cycle-" + arkham_id[:2]
        else:
            unit = "cycle-unknown"
    else:
        parts = PurePosixPath(*Path(source_file).parts).parts
        if len(parts) >= 2:
            unit = parts[0]
        elif parts:
            unit = PurePosixPath(parts[-1]).stem
        else:
            unit = "(root)"
    return str(PurePosixPath(pack) / unit)


def compute_sha256(path: Path) -> str:
    """Compute SHA-256 hex digest of a file's contents."""
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def atomic_write_json(path: Path, data: dict) -> None:
    """Write JSON via .tmp + os.replace for atomicity.

    Uses indent=2, ensure_ascii=False, sort_keys=False to preserve cards order.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(
            json.dumps(data, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        tmp.replace(path)
    finally:
        # Defensive cleanup if replace failed.
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass


def build_card_record(
    path: Path,
    source_dir: Path,
    obj: dict,
    pack: str = PACK,
    tolerant: bool = False,
) -> dict:
    """Parse one decomposed card JSON into a per-card index record.

    ``obj`` is the already-parsed JSON for ``path``; the caller parses each file
    exactly once (and uses the same object to decide whether the file is in
    scope), so this function never re-reads the file.

    Hard exits: 40 (GMNotes), 41 (grid), 43 (empty CustomDeck). 40 and 43 are
    STRICT-mode only — under ``tolerant`` (``--coverage``) both are demoted to
    row anomalies so a coverage walk cannot be aborted by one object.
    Row-level anomalies (kept + flagged): card_id_invalid, multi_deck,
    deckkey_mismatch, cell_out_of_bounds, and (tolerant only)
    gmnotes_sidecar_resolved, gmnotes_unresolved, no_custom_deck.
    """
    location = str(path)
    source_file = str(path.relative_to(source_dir))

    anomalies: list[str] = []

    arkham_id, gmnotes_anomaly = _parse_gmnotes_id(
        obj, location, tolerant=tolerant, path=path, pack_root=source_dir
    )
    if gmnotes_anomaly:
        anomalies.append(gmnotes_anomaly)
    name = obj.get("Nickname", "")
    sideways = bool(obj.get("SidewaysCard", False))

    # Validate CardID (soft — keep-and-flag, never sys.exit).
    card_id = _coerce_card_id(obj.get("CardID"))
    if card_id is None:
        anomalies.append(ANOMALY_CARD_ID_INVALID)

    custom_deck = obj.get("CustomDeck", {})
    if not custom_deck:
        if not tolerant:
            print(
                f"Card invariant violation: empty CustomDeck at {path} "
                f"(--coverage records this as a row anomaly instead)",
                file=sys.stderr,
            )
            sys.exit(43)
        anomalies.append(ANOMALY_NO_CUSTOM_DECK)
        # TOTAL, INERT values — never leave these unbound. The whole
        # deck-derivation block below is skipped, and every downstream
        # dereference (deck_key at the record/CSV/anomaly-detail sites, and
        # entry.get(...) for FaceURL/NumWidth/NumHeight/BackURL/UniqueBack)
        # then works untouched: {}.get(k, d) is d. Leaving them unbound
        # raises UnboundLocalError and writes NO output files at all.
        deck_key = ""
        entry: dict = {}
        custom_deck_entry = None
    else:
        # Select the single deck entry the SAME way the reuse source does,
        # then validate the CardID//100 relationship rather than using it as
        # selector.
        deck_key = next(iter(custom_deck))
        if len(custom_deck) != 1:
            anomalies.append(ANOMALY_MULTI_DECK)
            # Disambiguate by re-selecting the entry whose key ==
            # str(CardID//100).
            if card_id is not None:
                expected_key = str(card_id // 100)
                if expected_key in custom_deck:
                    deck_key = expected_key
        entry = custom_deck[deck_key]
        custom_deck_entry = entry

        # Validate the CardID//100 invariant (skipped when card_id is invalid).
        if card_id is not None:
            expected_key = str(card_id // 100)
            if expected_key != deck_key:
                anomalies.append(ANOMALY_DECKKEY_MISMATCH)

    # FRONT derivation. The FACE image is the verdict driver; for a Custom_PDF
    # it lives in CustomPDF.PDFUrl rather than in a CustomDeck entry, so
    # resolve_image_source() picks by object shape and records which field it
    # used. face_url/face_source therefore always describe the image actually
    # judged — for an ordinary card this is byte-identical to
    # entry.get("FaceURL", "").
    face_url, image_source_field = resolve_image_source(obj, custom_deck_entry)
    nw = _coerce_int(entry.get("NumWidth", 0), location, "NumWidth")
    nh = _coerce_int(entry.get("NumHeight", 0), location, "NumHeight")

    # x/y default to the typed sentinel (None). cell_index is None only when
    # card_id is invalid (no usable CardID).
    face_cell_index: int | None = None
    face_x: int | None = None
    face_y: int | None = None

    if card_id is not None and custom_deck_entry is not None:
        cell = card_id % 100
        face_cell_index = cell
        capacity = nw * nh
        if cell >= capacity:
            anomalies.append(ANOMALY_CELL_OUT_OF_BOUNDS)
            # Keep raw cell_index (informational); x/y stay sentinel.
        else:
            face_x = cell % nw
            face_y = cell // nw

    # BACK derivation: two-branch rule keyed off the authoritative UniqueBack.
    back_url = entry.get("BackURL", "")
    unique_back = bool(entry.get("UniqueBack", False))

    back: dict | None
    if back_url == "":
        # No back at all: all back_* columns empty, JSON back=null.
        back = None
    elif unique_back:
        # Gridded mirror back: mirrors the face grid + cell (incl. sentinel).
        back = {
            "url": back_url,
            "source": classify_host(back_url),
            "num_width": nw,
            "num_height": nh,
            "cell_index": face_cell_index,
            "x": face_x,
            "y": face_y,
            "single_image": False,
        }
    else:
        # Single shared cardback: one whole image, a 1x1 cell at origin.
        back = {
            "url": back_url,
            "source": classify_host(back_url),
            "num_width": 1,
            "num_height": 1,
            "cell_index": 0,
            "x": 0,
            "y": 0,
            "single_image": True,
        }

    # Grid/cell are null — NEVER 0 — when there is no CustomDeck: a 0x0 grid
    # would read as a real grid of capacity zero.
    if custom_deck_entry is None:
        grid_nw: int | None = None
        grid_nh: int | None = None
    else:
        grid_nw = nw
        grid_nh = nh

    record = {
        "name": name,
        "arkham_id": arkham_id,
        "card_id": card_id,
        "deck_key": deck_key,
        "face": {
            "url": face_url,
            "source": classify_host(face_url),
            "num_width": grid_nw,
            "num_height": grid_nh,
            "cell_index": face_cell_index,
            "x": face_x,
            "y": face_y,
        },
        "back": back,
        "unique_back": unique_back,
        "sideways": sideways,
        "pack": pack,
        "image_language": image_language(face_url),
        "image_source_field": image_source_field,
        "unit_key": derive_unit_key(pack, source_file, arkham_id),
        "source_file": source_file,
        "anomaly": ";".join(anomalies),
    }
    return record


def _csv_cell(value) -> str:
    """Render a JSON-side value as a CSV cell (None -> empty string).

    bool renders as "True"/"False" via str() (bool is an int subclass), so no
    special-casing is needed beyond the None -> "" rule.
    """
    if value is None:
        return ""
    return str(value)


def record_to_csv_row(rec: dict) -> list[str]:
    """Flatten a per-card record into the fixed 23-column CSV row order."""
    face = rec["face"]
    back = rec["back"]
    if back is None:
        back_url = back_source = ""
        back_nw = back_nh = back_cell = back_x = back_y = None
    else:
        back_url = back["url"]
        back_source = back["source"]
        back_nw = back["num_width"]
        back_nh = back["num_height"]
        back_cell = back["cell_index"]
        back_x = back["x"]
        back_y = back["y"]

    return [
        _csv_cell(rec["name"]),
        _csv_cell(rec["arkham_id"]),
        _csv_cell(rec["card_id"]),
        _csv_cell(rec["deck_key"]),
        _csv_cell(face["url"]),
        _csv_cell(face["source"]),
        _csv_cell(face["num_width"]),
        _csv_cell(face["num_height"]),
        _csv_cell(face["cell_index"]),
        _csv_cell(face["x"]),
        _csv_cell(face["y"]),
        _csv_cell(back_url),
        _csv_cell(back_source),
        _csv_cell(back_nw),
        _csv_cell(back_nh),
        _csv_cell(back_cell),
        _csv_cell(back_x),
        _csv_cell(back_y),
        _csv_cell(rec["unique_back"]),
        _csv_cell(rec["sideways"]),
        _csv_cell(rec["pack"]),
        _csv_cell(rec["source_file"]),
        _csv_cell(rec["anomaly"]),
    ]


def write_csv(path: Path, records: list[dict]) -> None:
    """Write the index CSV (RFC-4180 quoting, UTF-8, \\n line terminator)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        with tmp.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.writer(fh, lineterminator="\n")
            writer.writerow(CSV_HEADER)
            for rec in records:
                writer.writerow(record_to_csv_row(rec))
        tmp.replace(path)
    finally:
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass


def build_anomaly_list(records: list[dict], include_pack: bool = False) -> list[dict]:
    """Build the structured manifest/JSON anomaly list, sorted deterministically.

    Each kept row carrying one or more codes contributes one entry per code,
    with a human-readable detail string for the out-of-bounds case.

    ``include_pack`` prepends the owning pack (and adds it to the sort key) for
    the coverage report, where source_file is only unique within a pack. The
    index's own list is unchanged.
    """
    entries: list[dict] = []
    for rec in records:
        if not rec["anomaly"]:
            continue
        codes = rec["anomaly"].split(";")
        face = rec["face"]
        for code in codes:
            detail = ""
            if code == ANOMALY_CELL_OUT_OF_BOUNDS:
                nw = face["num_width"]
                nh = face["num_height"]
                detail = (
                    f"face_cell_index={face['cell_index']} >= "
                    f"capacity={nw * nh} ({nw}x{nh}) for deck_key={rec['deck_key']}"
                )
            elif code == ANOMALY_DECKKEY_MISMATCH:
                # deckkey_mismatch is only recorded when card_id is valid (§5.3),
                # so rec["card_id"] is always non-None here.
                expected = str(rec["card_id"] // 100)
                detail = f"deck_key={rec['deck_key']} != str(CardID//100)={expected}"
            elif code == ANOMALY_MULTI_DECK:
                detail = "more than one CustomDeck entry"
            elif code == ANOMALY_CARD_ID_INVALID:
                detail = "missing or non-integer CardID"
            elif code == ANOMALY_GMNOTES_SIDECAR_RESOLVED:
                detail = ("GMNotes absent or unparseable inline; id resolved "
                          "from an external .gmnotes sidecar")
            elif code == ANOMALY_GMNOTES_UNRESOLVED:
                detail = ("GMNotes absent or unparseable and no .gmnotes "
                          "sidecar resolved")
            elif code == ANOMALY_NO_CUSTOM_DECK:
                detail = ("object has no CustomDeck; grid and cell fields are "
                          "null and the face image is taken from "
                          f"{rec['image_source_field']}")
            entry = {
                "card_id": rec["card_id"],
                "arkham_id": rec["arkham_id"],
                "name": rec["name"],
                "source_file": rec["source_file"],
                "code": code,
                "detail": detail,
            }
            if include_pack:
                entry = dict(pack=rec["pack"], **entry)
            entries.append(entry)
    if include_pack:
        entries.sort(key=lambda e: (e["pack"], e["source_file"], e["code"]))
    else:
        entries.sort(key=lambda e: (e["source_file"], e["code"]))
    return entries


def build_counts(records: list[dict], json_files_scanned: int) -> dict:
    """Aggregate counts for the JSON + manifest counts block."""
    face_source = {"R2": 0, "Steam": 0, "other": 0}
    back_source = {"R2": 0, "Steam": 0, "other": 0}
    anomaly_count = 0
    for rec in records:
        face_source[rec["face"]["source"]] += 1
        if rec["back"] is not None:
            back_source[rec["back"]["source"]] += 1
        if rec["anomaly"]:
            anomaly_count += 1
    return {
        "json_files_scanned": json_files_scanned,
        "cards_written": len(records),
        "face_source": face_source,
        "back_source": back_source,
        "anomalies": anomaly_count,
    }


def _korean_pct(korean: int, denominator: int):
    """Percent Korean, or None when nothing was measurable.

    ``denominator == 0`` means every object in the bucket was ``unknown``.
    Emitting 0.0 there would be a lie — it says "measured, nothing Korean"
    where the truth is "nothing was measurable" — so the value is null in JSON
    and the empty string in CSV. Never 0.0, never a ZeroDivisionError.
    """
    if denominator <= 0:
        return None
    return round(korean / denominator * 100, 2)


def _new_bucket() -> dict:
    return {
        "objects": 0,
        LANG_KOREAN: 0,
        LANG_ENGLISH: 0,
        LANG_UNKNOWN: 0,
        "back": {LANG_KOREAN: 0, LANG_ENGLISH: 0, LANG_UNKNOWN: 0},
        "face_back_mismatch": 0,
        "anomalies": 0,
    }


def _accumulate(bucket: dict, rec: dict) -> None:
    face_lang = rec["image_language"]
    back = rec["back"]
    back_lang = image_language(back["url"] if back is not None else "")
    bucket["objects"] += 1
    bucket[face_lang] += 1
    bucket["back"][back_lang] += 1
    # A "mismatch" is a korean/english CROSSING — the population a
    # face-and-back-combined verdict rule would move. An unknown on either
    # side is a non-measurement, not a disagreement, so it never counts.
    if (face_lang != back_lang
            and face_lang != LANG_UNKNOWN and back_lang != LANG_UNKNOWN):
        bucket["face_back_mismatch"] += 1
    if rec["anomaly"]:
        bucket["anomalies"] += 1


def _bucket_to_row(bucket: dict) -> dict:
    denominator = bucket[LANG_KOREAN] + bucket[LANG_ENGLISH]
    return {
        "objects": bucket["objects"],
        "korean": bucket[LANG_KOREAN],
        "english": bucket[LANG_ENGLISH],
        "unknown": bucket[LANG_UNKNOWN],
        "denominator": denominator,
        "korean_pct": _korean_pct(bucket[LANG_KOREAN], denominator),
        "back": dict(bucket["back"]),
        "face_back_mismatch": bucket["face_back_mismatch"],
        "anomalies": bucket["anomalies"],
    }


def build_coverage_report(
    records: list[dict],
    sources: list[dict],
    generated_at: str,
    incumbent_comparison=None,
) -> dict:
    """Build the korean_coverage_report.json document (design §3.1).

    A pure function over ``records`` — no I/O — so the rollup is unit-testable
    in isolation. Objects are keyed by (pack, source_file) and NEVER collapsed
    by id: a card physically present in two units is counted in both, and no
    ``dict[id] = record`` assignment exists anywhere in this function. That is
    the structural answer to the incumbent's last-write-wins id map.
    """
    totals = _new_bucket()
    units: dict = {}
    unknown_breakdown: dict = {}
    id_units: dict = {}
    disagreement_objects = 0
    disagreement_ids = set()

    for rec in records:
        unit_key = rec["unit_key"]
        bucket = units.get(unit_key)
        if bucket is None:
            bucket = units[unit_key] = _new_bucket()
        _accumulate(bucket, rec)
        _accumulate(totals, rec)

        face_lang = rec["image_language"]
        if face_lang == LANG_UNKNOWN:
            label = unknown_host_label(rec["face"]["url"] or "")
            unknown_breakdown[label] = unknown_breakdown.get(label, 0) + 1

        arkham_id = rec["arkham_id"]
        if arkham_id:
            # An object contributes its id to the incumbent's lang_ids set
            # purely by existing under a Korean pack, so every parseable id is
            # scored COVERED there. Disagreement is therefore derivable from
            # this walk alone — no incumbent code is executed.
            if face_lang != LANG_KOREAN:
                disagreement_objects += 1
                disagreement_ids.add(arkham_id)
            owners = id_units.get(arkham_id)
            if owners is None:
                owners = id_units[arkham_id] = {}
            owners.setdefault(unit_key, set()).add(face_lang)

    unit_rows = []
    for unit_key in sorted(units):
        pack, _, unit = unit_key.partition("/")
        row = {
            "unit_key": unit_key,
            "pack": pack,
            "unit": unit,
            "unit_key_source": UNIT_KEY_SOURCE.get(pack, "directory"),
        }
        row.update(_bucket_to_row(units[unit_key]))
        unit_rows.append(row)

    multi_unit_ids = [i for i, owners in id_units.items() if len(owners) > 1]
    conflicts = []
    for arkham_id in sorted(multi_unit_ids):
        owners = id_units[arkham_id]
        verdicts = set()
        for langs in owners.values():
            verdicts |= langs
        if len(verdicts) < 2:
            continue
        conflicts.append({
            "id": arkham_id,
            "units": [
                {"unit_key": uk, "image_language": lang}
                for uk in sorted(owners)
                for lang in sorted(owners[uk])
            ],
        })

    report = {
        "schema_version": COVERAGE_SCHEMA_VERSION,
        "report_kind": COVERAGE_REPORT_KIND,
        "generated_at": generated_at,
        "supersedes": {
            "artifact": INCUMBENT_ARTIFACT,
            "generator": INCUMBENT_GENERATOR,
            "scope": "judging whether Korean langpack content renders Korean art",
            "reason": (
                "the superseded metric decides coverage by GMNotes-id set "
                "membership and reads no image URL, so an object carrying the "
                "right id while pointing at the English Steam host scores as "
                "covered"
            ),
            "not_superseded": (
                "the inventory of ids REQUIRED but ABSENT from the Korean tree "
                "(Korean_report.json's content[].missing[]). This report never "
                "reads the English base tree and cannot produce that list."
            ),
            "correction": (
                "Korean_report.json's Barkham 0/59 and Midwinter 0/48 are "
                "staleness (generated 2026-08-06 on Windows), NOT an "
                "id-matching blind spot. Re-running its generator against this "
                "tree yields 57/59 and 47/48."
            ),
            "documented_in": DOC_POINTER,
        },
        "method": {
            "counting_unit": "object",
            "verdict_driver": "face",
            "image_url_field": {
                "card": "CustomDeck[<first key>].FaceURL",
                "custom_pdf": "CustomPDF.PDFUrl",
            },
            "host_map": {
                R2_HOST_FRAGMENT: LANG_KOREAN,
                STEAM_HOST_FRAGMENT: LANG_ENGLISH,
            },
            "unknown_policy": (
                "reported separately; EXCLUDED from the denominator of "
                "korean_pct"
            ),
            "denominator": "korean + english",
            "duplicate_id_policy": (
                "objects are keyed by (pack, source_file) and never collapsed "
                "by id; a card physically present in two units is counted in "
                "both"
            ),
            "back_policy": (
                "recorded and rolled up independently; never contributes to "
                "the object verdict. face_back_mismatch counts korean/english "
                "crossings only — an unknown on either side is a "
                "non-measurement, not a disagreement"
            ),
        },
        "sources": sources,
        "totals": _bucket_to_row(totals),
        "unknown_breakdown": dict(
            sorted(unknown_breakdown.items(), key=lambda kv: kv[0])
        ),
        "units": unit_rows,
        "disagreement_with_incumbent": {
            "basis": (
                "An object contributes its GMNotes id to the incumbent's "
                "lang_ids set purely by existing under a Korean pack, so every "
                "object with a parseable id is scored COVERED by the "
                "incumbent. Disagreement is therefore computed entirely from "
                "this walk: parseable id AND image_language != 'korean'. No "
                "incumbent code is executed and no incumbent artifact is read."
            ),
            "objects": disagreement_objects,
            "distinct_ids": len(disagreement_ids),
            "caveats": [
                "Upper bound at id granularity: the incumbent intersects "
                "against required_ids from the English base tree, which this "
                "report never loads, so ids present in the Korean tree but not "
                "required are counted here and are 'orphans' (0) there.",
                "The incumbent dedupes by id; this figure counts objects. "
                "distinct_ids is the id-granularity companion.",
            ],
        },
        "multi_owner_ids": {
            "policy": (
                "declared, never collapsed — attribution of a reused card to a "
                "unit is a product decision, not derivable from the data "
                "(GMNotes carries no cycle field in Player Cards, and cycle is "
                "unreliable elsewhere)"
            ),
            "ids_in_multiple_units": len(multi_unit_ids),
            "verdict_conflict_count": len(conflicts),
            "verdict_conflicts": conflicts,
        },
        "anomalies": build_anomaly_list(records, include_pack=True),
        "incumbent_comparison": incumbent_comparison,
    }
    return report


def coverage_row_to_csv_row(row: dict) -> list[str]:
    """Flatten a per-unit coverage row into the fixed 15-column CSV order."""
    back = row["back"]
    return [
        _csv_cell(row["unit_key"]),
        _csv_cell(row["pack"]),
        _csv_cell(row["unit"]),
        _csv_cell(row["unit_key_source"]),
        _csv_cell(row["objects"]),
        _csv_cell(row["korean"]),
        _csv_cell(row["english"]),
        _csv_cell(row["unknown"]),
        _csv_cell(row["denominator"]),
        _csv_cell(row["korean_pct"]),
        _csv_cell(back[LANG_KOREAN]),
        _csv_cell(back[LANG_ENGLISH]),
        _csv_cell(back[LANG_UNKNOWN]),
        _csv_cell(row["face_back_mismatch"]),
        _csv_cell(row["anomalies"]),
    ]


def write_coverage_csv(path: Path, unit_rows: list[dict]) -> None:
    """Write the coverage CSV (15 columns, RFC-4180, UTF-8 no BOM, \\n)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        with tmp.open("w", encoding="utf-8", newline="") as fh:
            writer = csv.writer(fh, lineterminator="\n")
            writer.writerow(COVERAGE_CSV_HEADER)
            for row in unit_rows:
                writer.writerow(coverage_row_to_csv_row(row))
        tmp.replace(path)
    finally:
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass


def read_incumbent_report(path: Path, this_report_korean_pct):
    """READ (never import, exec or write) a Korean_report.json for comparison.

    Returns ``(comparison_or_None, ok)``. A missing or malformed file is a
    warning, not a hard exit: one stderr line naming the path and the reason,
    ``incumbent_comparison`` stays null, the run continues and still writes
    both coverage outputs, and the run exits 1.

    The try/except is load-bearing rather than defensive: a bare json.load
    failure happens to exit 1 as well, so without it the documented exit code
    could not distinguish the contract being honoured from an unhandled
    traceback.
    """
    try:
        with path.open(encoding="utf-8") as fh:
            data = json.load(fh)
        if not isinstance(data, dict):
            raise ValueError("top-level JSON value is not an object")
    except (OSError, ValueError) as exc:
        print(
            f"--incumbent-report unreadable: {path} ({exc.__class__.__name__}: "
            f"{exc}); incumbent_comparison left null",
            file=sys.stderr,
        )
        return None, False

    metadata = data.get("metadata")
    if not isinstance(metadata, dict):
        metadata = {}
    content = data.get("content")
    if not isinstance(content, dict):
        content = {}
    # Windows-generated reports key content as 'campaign\\The Dunwich Legacy'.
    # Normalise separators before anything derived from a key is stored.
    normalised_keys = sorted(str(k).replace("\\", "/") for k in content)

    total_found = metadata.get("total_found")
    total_required = metadata.get("total_required")
    if total_found is None and total_required is None:
        incumbent_total = None
    else:
        incumbent_total = f"{total_found} / {total_required}"

    headline_delta = None
    incumbent_pct_value = _parse_percent(metadata.get("overall_completion"))
    if incumbent_pct_value is not None and this_report_korean_pct is not None:
        headline_delta = round(this_report_korean_pct - incumbent_pct_value, 2)

    return {
        "path": str(path),
        "read_only": True,
        "incumbent_last_updated": metadata.get("last_updated"),
        "incumbent_overall_completion": metadata.get("overall_completion"),
        "incumbent_total": incumbent_total,
        "incumbent_content_keys": normalised_keys,
        "this_report_korean_pct": this_report_korean_pct,
        "headline_delta_points": headline_delta,
        "per_unit_comparison": "not attempted",
        "per_unit_comparison_reason": (
            "the incumbent keys content as 'campaign\\The Dunwich Legacy' "
            "(Windows separators, display names); this report keys as "
            "'campaigns/TheDunwichLegacy.2898f6' (decomposed directory names). "
            "Mapping the two requires a name table that does not exist; "
            "inventing a fuzzy match would fabricate precision."
        ),
        "separator_normalisation": (
            "incumbent content keys are read with '\\\\' -> '/' applied before "
            "any comparison"
        ),
    }, True


def _display_source_path(pack_root: Path) -> str:
    """Render a pack root relative to the decomposed tree when it lives there.

    Keeps sources[].path stable and short for the canonical layout (the design
    §3.1 form) while still naming an arbitrary --source-dir honestly.
    """
    try:
        rel = pack_root.resolve().relative_to(DEFAULT_DECOMPOSED_ROOT.resolve())
        return str(PurePosixPath(*rel.parts))
    except (ValueError, OSError):
        return pack_root.as_posix()


def _parse_percent(value):
    """Parse '86.70 %' into 86.7; None on anything unparseable."""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    if not isinstance(value, str):
        return None
    match = re.search(r"-?\d+(?:\.\d+)?", value)
    if not match:
        return None
    try:
        return float(match.group(0))
    except ValueError:
        return None


def main(argv=None) -> int:
    args = parse_args(argv)

    out_dir: Path = args.out_dir
    tolerant: bool = args.coverage
    pack_pairs = args.pack_pairs

    for pack, pack_root in pack_pairs:
        if not pack_root.exists():
            label = "--source-dir" if args.single_pack_default else "--packs"
            print(
                f"{label} does not exist: {pack_root} (pack {pack})",
                file=sys.stderr,
            )
            return 43

    records: list[dict] = []
    sources: list[dict] = []
    json_files_scanned = 0
    for pack, pack_root in pack_pairs:
        pack_objects = 0
        for path in sorted(pack_root.rglob("*.json")):
            with path.open(encoding="utf-8") as fh:
                peek = json.load(fh)
            # Skip files lacking both CardID and CustomDeck (not counted).
            # Under --coverage the predicate is widened to admit Custom_PDF
            # guide / campaign-log objects, which carry neither; container
            # JSONs (the pack-level bags) still skip correctly.
            if "CardID" not in peek and "CustomDeck" not in peek:
                if not (tolerant and peek.get("Name") == "Custom_PDF"):
                    continue
            json_files_scanned += 1
            pack_objects += 1
            records.append(
                build_card_record(path, pack_root, peek, pack, tolerant)
            )
        sources.append({
            "pack": pack,
            "path": _display_source_path(pack_root),
            "unit_key_source": UNIT_KEY_SOURCE.get(pack, "directory"),
            "objects": pack_objects,
        })

    # Sort by (pack, arkham_id, card_id, source_file) for deterministic output.
    # card_id can be None (card_id_invalid); sort those last via a typed key.
    # With one pack this is identical to the pre-multi-pack key; `pack` in the
    # leading position is what makes the tuple a total order across packs even
    # if two packs produced the same relative path.
    records.sort(key=lambda r: (
        r["pack"],
        r["arkham_id"],
        (r["card_id"] is None, r["card_id"] or 0),
        r["source_file"],
    ))

    counts = build_counts(records, json_files_scanned)
    anomaly_entries = build_anomaly_list(records)

    drift = counts["json_files_scanned"] != counts["cards_written"]
    if drift:
        print(
            f"Count drift: json_files_scanned={counts['json_files_scanned']} "
            f"!= cards_written={counts['cards_written']}",
            file=sys.stderr,
        )

    warnings_emitted = bool(anomaly_entries) or drift

    if args.single_pack_default:
        print(
            f"Loaded {json_files_scanned} player card files "
            f"from {pack_pairs[0][1]}."
        )
    else:
        breakdown = ", ".join(
            f"{s['pack']} {s['objects']}" for s in sources
        )
        print(
            f"Loaded {json_files_scanned} objects from "
            f"{len(pack_pairs)} packs ({breakdown})."
        )
    print(
        f"Built {len(records)} cards "
        f"(face: R2 {counts['face_source']['R2']} / Steam {counts['face_source']['Steam']} "
        f"/ other {counts['face_source']['other']}; "
        f"back: R2 {counts['back_source']['R2']} / Steam {counts['back_source']['Steam']} "
        f"/ other {counts['back_source']['other']}; anomalies {counts['anomalies']})."
    )
    for entry in anomaly_entries:
        print(
            f"ANOMALY {entry['code']}: card_id={entry['card_id']} "
            f"arkham_id={entry['arkham_id']} source_file={entry['source_file']} "
            f"{entry['detail']}",
            file=sys.stderr,
        )

    generated_at = datetime.now(timezone.utc).isoformat()

    # `source_dir` is kept verbatim (the pack subpath, even when --source-dir
    # overrides it) for backward compatibility; `sources[]` is authoritative in
    # all modes.
    if len(pack_pairs) == 1:
        source_dir_field = PACKS.get(pack_pairs[0][0], SOURCE_SUBPATH)
    else:
        source_dir_field = "(multiple; see sources[])"

    index_doc = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": generated_at,
        "source_dir": source_dir_field,
        "sources": sources,
        "counts": counts,
        "anomalies": anomaly_entries,
        "cards": records,
    }

    coverage_report = None
    if args.coverage:
        coverage_report = build_coverage_report(records, sources, generated_at)
        totals = coverage_report["totals"]
        if args.incumbent_report is not None:
            comparison, ok = read_incumbent_report(
                args.incumbent_report, totals["korean_pct"]
            )
            coverage_report["incumbent_comparison"] = comparison
            if not ok:
                warnings_emitted = True
        pct = totals["korean_pct"]
        pct_text = "n/a (denominator 0)" if pct is None else f"{pct}%"
        print(
            f"Coverage (face image language): korean {totals['korean']} "
            f"/ english {totals['english']} / unknown {totals['unknown']}"
        )
        print(
            f"  headline: {pct_text} Korean (denominator "
            f"{totals['denominator']}, unknown excluded and declared)"
        )
        print(
            "  NOTE: this is far below Korean_report.json's headline BY "
            "DESIGN — that metric counts"
        )
        print(
            "        id presence and never reads an image URL. See "
            + DOC_POINTER + "."
        )
        disagreement = coverage_report["disagreement_with_incumbent"]
        print(
            f"  disagreement with the incumbent metric: "
            f"{disagreement['objects']} objects / "
            f"{disagreement['distinct_ids']} distinct ids"
        )
        multi = coverage_report["multi_owner_ids"]
        print(
            f"  face/back mismatch: {totals['face_back_mismatch']} objects   "
            f"multi-owner ids: {multi['ids_in_multiple_units']} "
            f"({multi['verdict_conflict_count']} with conflicting verdicts)"
        )
        measurable = [
            u for u in coverage_report["units"] if u["korean_pct"] is not None
        ]
        bottom = sorted(
            measurable, key=lambda u: (u["korean_pct"], -u["objects"], u["unit_key"])
        )[:5]
        if bottom:
            print(
                "Bottom 5 units by korean_pct: "
                + " | ".join(
                    f"{u['unit_key']} {u['korean_pct']}% ({u['objects']})"
                    for u in bottom
                )
            )

    if args.dry_run:
        print("(dry-run mode — no files written)")
        return 1 if warnings_emitted else 0

    out_dir.mkdir(parents=True, exist_ok=True)

    json_path = out_dir / "korean_card_index.json"
    csv_path = out_dir / "korean_card_index.csv"
    manifest_path = out_dir / "manifest.json"
    coverage_json_path = out_dir / "korean_coverage_report.json"
    coverage_csv_path = out_dir / "korean_coverage_report.csv"

    atomic_write_json(json_path, index_doc)
    write_csv(csv_path, records)

    verify_paths = [json_path, csv_path]
    outputs = {
        "korean_card_index.json": {"sha256": compute_sha256(json_path)},
        "korean_card_index.csv": {"sha256": compute_sha256(csv_path)},
    }
    if coverage_report is not None:
        atomic_write_json(coverage_json_path, coverage_report)
        write_coverage_csv(coverage_csv_path, coverage_report["units"])
        verify_paths.extend([coverage_json_path, coverage_csv_path])
        outputs["korean_coverage_report.json"] = {
            "sha256": compute_sha256(coverage_json_path)
        }
        outputs["korean_coverage_report.csv"] = {
            "sha256": compute_sha256(coverage_csv_path)
        }

    json_sha = outputs["korean_card_index.json"]["sha256"]
    csv_sha = outputs["korean_card_index.csv"]["sha256"]

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "indexer": {
            "script": INDEXER_SCRIPT,
            "version": SCHEMA_VERSION,
        },
        "mode": "index+coverage" if args.coverage else "index",
        "packs": [pack for pack, _ in pack_pairs],
        "source_dir": source_dir_field,
        "sources": sources,
        "counts": counts,
        "anomalies": anomaly_entries,
        "outputs": outputs,
    }
    atomic_write_json(manifest_path, manifest)

    # Re-read every data output and verify sha256 matches the manifest claim.
    declared = manifest["outputs"]
    for path in verify_paths:
        actual = compute_sha256(path)
        expected = declared[path.name]["sha256"]
        if actual != expected:
            print(
                f"sha256 mismatch on re-read: {path.name} "
                f"declared={expected!r} actual={actual!r}",
                file=sys.stderr,
            )
            return 42

    print(f"Wrote {json_path}  sha256={json_sha[:16]}...")
    print(f"Wrote {csv_path}  sha256={csv_sha[:16]}...")
    if coverage_report is not None:
        print(
            f"Wrote {coverage_json_path}  "
            f"sha256={outputs['korean_coverage_report.json']['sha256'][:16]}..."
        )
        print(
            f"Wrote {coverage_csv_path}  "
            f"sha256={outputs['korean_coverage_report.csv']['sha256'][:16]}..."
        )
    print(f"Wrote {manifest_path}")

    return 1 if warnings_emitted else 0


if __name__ == "__main__":
    sys.exit(main())
